### ISSUE TITLE
Classification Experiment

### ISSUE THREAD

**Issue by low5545** [VITA-Group/INSP#2]
Thanks for the interesting work!
I would like to ask how is the classification on INSP-ConvNet done? Since INSP-ConvNet yields another INR, how do you perform the classification on this output (i.e. how do you collapse the resulting INR to a finite dimensional vector and apply softmax)?

**Comment by Ir1d** [comment]
Thanks for your interest! For classification, we can let the fusion mlp output 10 channel output, so we can use the argmax to obtain the class.

**Comment by low5545** [comment]
But isn't this 10 channel output a function of the input image position? This seems more like an image segmentation than image classification.

**Comment by Ir1d** [comment]
oh i see. yeah we actually need an additional global pooling to obtain a single class label

**Comment by low5545** [comment]
Thanks for the clarification. Is it right that the global pooling is done across the 10D vectors associated to a finite set of sampled pixel locations?

**Comment by Ir1d** [comment]
We need to sample some  (e.g. N) pixel locations, then we have (N, 10) in the end. We do average pooling to make the final result (1, 10).

**Comment by low5545** [comment]
Thanks for the explanation!
